### PR TITLE
Added resize binding to brace resize function to handle dynamic resize.

### PR DESCRIPTION
**Pull request by Durindo**
I was building a workspace with react-ace and I noticed that since the last update the resize did not work properly anymore. I just added a new prop condition on the height and bound it to the brace resize function.

### CODE REVIEW

**Comment by securingsincity** [comment]
I merged these changes into the 3.0 release but not through this PR thanks @Durindo

**Comment by janesconference** [comment]
Can't see them in the code - in fact, resize seems never called in [ace.jsx](https://github.com/securingsincity/react-ace/blob/master/src/ace.jsx). I have the same problem as @Durindo in react-ace@3.1.0.

**Comment by Durindo** [comment]
I finally found some time to check it, and the change is not there as pointed out by @janesconference .
I rebuilt my project using both the current 3.4.0 and a fork of it with the PR change, and the behavior with the resize call is more robust.

**Comment by andrew-luminal** [comment]
Same here, would love to see this properly merged in.

**Comment by securingsincity** [comment]
@Durindo @janesconference @andrew-luminal  don't know what happened before but it should be all set now.

**Pull request merged**
