### PR TITLE
Replacing `brace` with `ace-builds`.

### LINKED ISSUE #512: Move away from brace.
# Problem

react-ace is currently using [brace](https://github.com/thlorenz/brace) as the underlying, browserified version of ace. Unfortunately brace is lagging a magnitude of versions behind and any change (feature, bug fix) to ace needs to propagate through brace before it ends up in react-ace. brace's development is currently stalling, with the last commit being done in February, issues not being answered and even PRs (like https://github.com/thlorenz/brace/pull/139) not being accepted and merged. Therefore I would suggest looking for an alternative which allows to benefit from ace development.

## References

Progress on: #

### PR DESCRIPTION
**Pull request by dennisoelkers**
# What's in this PR?
Currently, `react-ace` is using `brace` for bundling the underlying ace editor's files. `brace` unfortunately is several versions behind the official release. Therefore this PR is moving from `brace` to the official `ace-builds` distribution.

## List the changes you made and your reasons for them.

* Replacing `brace` package with `ace-builds` and adapting imports accordingly
* Adapting tests to newly added css classes

### Fixes #
Fixes #512.
### Progress on: #

### CODE REVIEW

**Comment by dennisoelkers** [comment]
@securingsincity: Unfortunately the tests related to the `onFocus` callbacks do not currently work. Maybe you have an idea why?

**Comment by manubb** [comment]
Hello.
Replacing:
```js
const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
```
with
```js
const jsdom = new JSDOM('<!doctype html><html><body><div id="app"></div></body></html>');
```
in `/tests/setup.js` fixes the problems with focus tests.

**Comment by dennisoelkers** [comment]
Thanks, @manubb!

@securingsincity, are you interested in checking if this PR makes sense for you?

**Comment by manubb** [comment]
I tested this update of react-ace on my project and it works as expected which is really cool!

I suggest to fix `/tests/src/ace.spec.js` in the following way:
- restore `mountOptions` on lines 335 and 360
- fix the undo test (which is causing the failure):
```js
it('should keep initial value after undo event', (done) => {
  const onInput = () => {
    const editor = wrapper.instance().editor;
    editor.undo();
    expect(editor.getValue()).to.equal('foobar');
    done()
  };

  const wrapper = mount(<AceEditor value="foobar" onInput={onInput} />, mountOptions);
});
```

**Comment by dennisoelkers** [comment]
Thanks for the great hint, @manubb! I have to admit that I am not used to `mocha`, but that did the trick.

**Comment by securingsincity** [comment]
This looks great. I'll set this up for a new major release. along with a couple other small things that were just opened. Thanks so much @dennisoelkers @manubb

**Pull request merged**
