### PR TITLE
use babel and browserify standalone for build

### PR DESCRIPTION
**Pull request by chentsulin**
use `babel`, `browserify` standalone and npm scritps to clearify build steps.

- use babel compile `src` to `lib`, then this module can be used without any compilation in commonjs environment. So user can use this without `.jsx` and exclude compile for `node_modules` for faster development cycle.
- use browserify standalone compile src to [UMD](https://github.com/umdjs/umd) module, so this can be be used as commonjs, amd, global module.
- add some npm scripts to lifecycle hook for some automation.

### CODE REVIEW

**Comment by chentsulin** [comment]
I have no ideas why `npm install` fail in node 0.10. Any ideas here?

**Comment by chentsulin** [comment]
@securingsincity  
It's hard for me to done every right using `browserify` and `gulp` (including react as external), if you are interested, I can prepare a webpack solution PR.

**Comment by securingsincity** [comment]
@chentsulin absolutely interested in a webpack solution definitely seems like thats where the community is headed.

**Comment by chentsulin** [comment]
OK, I will prepare a PR for webpack solution.

**Comment by chentsulin** [comment]
I thought this should be split into 3 step
1. use `babel` for es5 entry
2. replace `browserify` to `webpack`
3. replace `jshint` to `eslint`

**Comment by securingsincity** [comment]
@chentsulin I'm going to close this as your other pull request starts this process.

**Comment by chentsulin** [comment]
@securingsincity UMD module should have a module name to export to global. Which name do you want? `ReactAce`, `AceEditor` or any others?

**Comment by securingsincity** [comment]
ReactAce would make the most sense IMO

**Pull request closed without merging**
