### PR TITLE
removed react from dependency

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
# What's in this PR?
https://github.com/securingsincity/react-ace/issues/279

## List the changes you made and your reasons for them.
- transfered react & react-dom from dependency to peer dependency
Make sure any changes to code include changes to documentation.

### CODE REVIEW

**Comment by securingsincity** [comment]
@M-ZubairAhmed do you mind changing `react-test-renderer`and making that a version 15 dependency? That should fix your build.

**Comment by M-ZubairAhmed** [comment]
to version previously should I change it too. ?

**Comment by M-ZubairAhmed** [comment]
i have changed `react-test-renderer` version to "^15.0.1"

**Comment by avanthay** [comment]
I think the build fails because npm installs the latest version of react and react-dom (version 16.x), and `package.json` did not list those versions in the peerDependencies. 
To fix it, the peerDependencies should also accept react and react-dom v16. Unfortunately react16 have some (minor) breaking changes, that mean the entire package needs to be tested against react16.

**Comment by securingsincity** [comment]
@M-ZubairAhmed thanks for the update. the latest merge actually adds support for react 16. Can you rebase your changes against that version?

**Comment by M-ZubairAhmed** [comment]
sure i just did pulled latest change and updated my pull request. Can you please check

**Pull request merged**
