### PR TITLE
New property SetOptions

### PR DESCRIPTION
**Pull request by jaszhix**
Allows you to set any other editor options in an object, like
editorProps.

### CODE REVIEW

**Comment by securingsincity** [comment]
#88 closed a similar issue. If there are other editorOptions that you want to include (enableSnippets was also added). Please open a separate PR. Thanks for contributing @jaszhix

**Comment by securingsincity** [comment]
Relooking at this. It might make more sense to open this up per several other issues opened #87 and #54 

@jaszhix  can you add some documentation on how this would be implemented for end users?

**Comment by jaszhix** [comment]
I added an example, and an entry in the README documentation.

**Comment by levithomason** [comment]
Looks great, is this getting merged soon?

**Pull request merged**
